apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgBCKWthipBbDf5NVzwdbNKYzwhLiNr8m2iJ95TJZAFzRwHFTjesiIxGMrJhQNJW+136nRxh6TtJi0rdr//tmodPDBfmsYxphH/lYldzEX5f5+Cl7SEku8DZ5es9wr/tpMtJFHrP21t+4n8FGSH2f6yofTD8vgb4JVpod3g4MrctsxEvhD31w0B+oCqspDi3B8+rD2hsxMlj1//A/EaexQccekNxQGMddJmbncIWOcU8yFXP+6gcdaiWBObJjKpXb0+S3uheOQyDc6NPM6XJR9sa0S76wRbj9cgQeOQ0RfjKsgxFuvTAjFiLyIbUGGi73SYKv/Sq86nhg+rXk8fLNdXefcLYuLl3lj16tYDKTYwnrR3zV5HeBUCr0QF7I5OFU4ScJ0tti1k7kF6AlNzcstZaQVRMtCB5szqAr/9+dK5JMgNB+QAKEu2IHTF8u5PvUsspcOwrVyRdhGlUD0ksxsVT9e9tvoZfIvsTSLtOkkpn0aW0IoP1Ra3v786pj4qgCuh5fwJGocljtONqD5pi15qi+acEKXFfVaREiuGZcbWxo7OcEqP8ie1Vg15Ec/gMeRUHbUGU0telOayoSmLVbLzdAlfsZw1BP22W6RxfKqp9qTvenKiFd6hgEbi4MVdt+Vpc9FuTYQZh71/xwLsWR5gPCG4zZgA0aTyHQ2OlBbQ2xN0Dt53DvTnVWikZ1RD8cssbE8yw++uRMDnnavufddnQkgYhd/qqM4nDewvYipOapnsnk0g4gVjT
    username: AgAv1288eE9B/pAJ0518hUiibj1XfFy1AmqBo55kQxNHsSXTX1xK+dWgwbZpPhE57WF097G6SaGIxAR2Pni65WCApRZnwmgXxjpdgAdmuucM7ySkHL89bIuULl+zOiO9ldqvEQV20fVV5gGk/ptyiQii+KnORCCsBS6TcjmjXB8R+koAi2wbesNTdmk0J2T7TG30QN4AmIulHpest1Prz4HUE3GB5AS6kRadDT3FyjxG/fcDl3Mki6hBdOgH3UoTPnQ0V8qeUmj7HsRCSgenvsDvCqmP0YI+FCruYRVLxtvFGph+Pdf92YvX55gloQ9eFrpYDR2mS9JzhU5pAIT7CW6zsFNSvB+GlVdmZ+sMW2nm6mQSL/Jct/6DMtcWr45kAjISC9vXZcIFWijN2WWOvRYdrU0/+x4H+YMco051iLzjC+wg2V3/SUeLFYLL8BNeqW0wS5QjFkHVAdAJdP7TZY0pmrU7ESXj96p+gcUGZEsXRWfmVrP4LNofTxGYON3jNEw+hOnFyKGLrGpElmNmNnYyfLJ1LuRMjNAUOSWAnG3J7vlInqEIJCLgl3cPcdhT0VDUBAEWHOHhlNTYoBWpqM6PJdXVFIYWLxJlEj2Um4u0qDHcFDy64aMGJsnJNQgf39TOc9Vr30ZJbvuZOyCQh3L1OT7W/gQiwUbVp1ajq+SnrgSpxny7j1TRbECEiCT44l1yWXowJrOXhBGpgw==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

